# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "dart"
    package: crypto
    schedule:
      interval: "daily"
    directory: "/"
  - package-ecosystem: "dart"
    package: flutter
    schedule:
      interval: "daily"
    directory: "/"
  - package-ecosystem: "dart"
    package: flutter_test
    schedule:
      interval: "daily"
    directory: "/"
  - package-ecosystem: "dart"
    package: flutter_lints
    schedule:
      interval: "daily"
    directory: "/"
